### ISSUE TITLE
現規則をリポジトリに含めてみてはどうでしょうか

### ISSUE THREAD

**Issue by rizaudo** [classcoins/rounge_policy#3]
ラウンジの現状の規則がリポジトリ上に無く、この新規則を読む際に具体的に現規則のどのような点が現状に即していないのかがわかりにくいと考えています。
そこで提案なのですが、現状の規約を画像ファイル等で良いのでリポジトリに含めていただけないでしょうか？
読む人が現規則の取り違えをしていた場合、リポジトリに含める事で取り違えによる齟齬をきたすことが無くなります。

一考のほどよろしくお願いします。

**Comment by naoyuky** [comment]
ご意見とpull requestありがとうございます。
ラウンジにて現物を確認したところ一部で誤植があったので、それを修正しました。

また、大変ややこしいことに、バージョンの古いガイドラインもラウンジに掲示されていました。
現行版は文字起こしされた方です。
旧版はPDFが残っていたので追加しています。こちらも参考になれば。

**Comment by rizaudo** [comment]
返答が遅くなってしまいすみません。
規則のリポジトリへの追加ありがとうございます。
