### ISSUE TITLE
pdf in a repo

### ISSUE THREAD

**Issue by Nymphium** [classcoins/rounge_policy#6]
I think it's unusual, or NOT good to put a PDF(non-plaintext file) into a repository. And the guidline written in plaintext is there.  BUT is the PDF needed?

**Comment by naoyuky** [comment]
There are two guideline(plaintext is the latest, and pdf is the older one), pleas confirm that they're not the same in content. So I added it for reference. This document is not need a change, like a distribution.
But I think it's unusual and not so good to add a pdf in a repo, too.

**Comment by Nymphium** [comment]
Oops, sorry. But PDF in a repo is irregular. Then, how about converting the PDF to a plaintext?

**Comment by naoyuky** [comment]
Hmm... That might be a good idea. I'll do so.
